export const BIBLE_BOOKS: Record<string, string[]> = {
  // Old Testament
  Genesis: ['Genesis', 'Gen', 'Ge', 'Gn'],
  Exodus: ['Exodus', 'Exod', 'Exo', 'Ex'],
  Leviticus: ['Leviticus', 'Lev', 'Le', 'Lv'],
  Numbers: ['Numbers', 'Num', 'Nu', 'Nm', 'Nb'],
  Deuteronomy: ['Deuteronomy', 'Deut', 'Dt'],
  Joshua: ['Joshua', 'Josh', 'Jos', 'Jsh'],
  Judges: ['Judges', 'Judg', 'Jdg', 'Jg'],
  Ruth: ['Ruth', 'Rth', 'Ru'],
  '1 Samuel': ['1 Samuel', '1 Sam', '1Sam', '1Sa', '1S', 'I Sam', 'I Samuel'],
  '2 Samuel': ['2 Samuel', '2 Sam', '2Sam', '2Sa', '2S', 'II Sam', 'II Samuel'],
  '1 Kings': ['1 Kings', '1 Kgs', '1Kgs', '1Ki', '1K', 'I Kgs', 'I Kings'],
  '2 Kings': ['2 Kings', '2 Kgs', '2Kgs', '2Ki', '2K', 'II Kgs', 'II Kings'],
  '1 Chronicles': ['1 Chronicles', '1 Chr', '1Chr', '1Ch', 'I Chr', 'I Chronicles'],
  '2 Chronicles': ['2 Chronicles', '2 Chr', '2Chr', '2Ch', 'II Chr', 'II Chronicles'],
  Ezra: ['Ezra', 'Ezr', 'Ez'],
  Nehemiah: ['Nehemiah', 'Neh', 'Ne'],
  Esther: ['Esther', 'Esth', 'Est', 'Es'],
  Job: ['Job', 'Jb'],
  Psalms: ['Psalms', 'Psalm', 'Ps', 'Psa', 'Psm'],
  Proverbs: ['Proverbs', 'Prov', 'Pro', 'Prv', 'Pr'],
  Ecclesiastes: ['Ecclesiastes', 'Eccl', 'Ecc', 'Ec', 'Qoh'],
  'Song of Solomon': ['Song of Solomon', 'Song of Songs', 'Song', 'SoS', 'Canticles', 'Cant'],
  Isaiah: ['Isaiah', 'Isa', 'Is'],
  Jeremiah: ['Jeremiah', 'Jer', 'Je', 'Jr'],
  Lamentations: ['Lamentations', 'Lam', 'La'],
  Ezekiel: ['Ezekiel', 'Ezek', 'Eze', 'Ezk'],
  Daniel: ['Daniel', 'Dan', 'Da', 'Dn'],
  Hosea: ['Hosea', 'Hos', 'Ho'],
  Joel: ['Joel', 'Joe', 'Jl'],
  Amos: ['Amos', 'Am'],
  Obadiah: ['Obadiah', 'Obad', 'Ob'],
  Jonah: ['Jonah', 'Jon', 'Jnh'],
  Micah: ['Micah', 'Mic', 'Mc'],
  Nahum: ['Nahum', 'Nah', 'Na'],
  Habakkuk: ['Habakkuk', 'Hab', 'Hb'],
  Zephaniah: ['Zephaniah', 'Zeph', 'Zep', 'Zp'],
  Haggai: ['Haggai', 'Hag', 'Hg'],
  Zechariah: ['Zechariah', 'Zech', 'Zec', 'Zc'],
  Malachi: ['Malachi', 'Mal', 'Ml'],

  // New Testament
  Matthew: ['Matthew', 'Matt', 'Mt'],
  Mark: ['Mark', 'Mrk', 'Mk', 'Mr'],
  Luke: ['Luke', 'Luk', 'Lk'],
  John: ['John', 'Joh', 'Jhn', 'Jn'],
  Acts: ['Acts', 'Act', 'Ac'],
  Romans: ['Romans', 'Rom', 'Ro', 'Rm'],
  '1 Corinthians': ['1 Corinthians', '1 Cor', '1Cor', '1Co', 'I Cor', 'I Corinthians'],
  '2 Corinthians': ['2 Corinthians', '2 Cor', '2Cor', '2Co', 'II Cor', 'II Corinthians'],
  Galatians: ['Galatians', 'Gal', 'Ga'],
  Ephesians: ['Ephesians', 'Eph', 'Ephes'],
  Philippians: ['Philippians', 'Phil', 'Php', 'Pp'],
  Colossians: ['Colossians', 'Col', 'Co'],
  '1 Thessalonians': ['1 Thessalonians', '1 Thess', '1Thess', '1Th', 'I Thess', 'I Thessalonians'],
  '2 Thessalonians': ['2 Thessalonians', '2 Thess', '2Thess', '2Th', 'II Thess', 'II Thessalonians'],
  '1 Timothy': ['1 Timothy', '1 Tim', '1Tim', '1Ti', 'I Tim', 'I Timothy'],
  '2 Timothy': ['2 Timothy', '2 Tim', '2Tim', '2Ti', 'II Tim', 'II Timothy'],
  Titus: ['Titus', 'Tit', 'Ti'],
  Philemon: ['Philemon', 'Philem', 'Phm', 'Pm'],
  Hebrews: ['Hebrews', 'Heb'],
  James: ['James', 'Jas', 'Jm'],
  '1 Peter': ['1 Peter', '1 Pet', '1Pet', '1Pe', '1Pt', 'I Pet', 'I Peter'],
  '2 Peter': ['2 Peter', '2 Pet', '2Pet', '2Pe', '2Pt', 'II Pet', 'II Peter'],
  '1 John': ['1 John', '1 Jn', '1Jn', '1Joh', '1Jo', 'I Jn', 'I John'],
  '2 John': ['2 John', '2 Jn', '2Jn', '2Joh', '2Jo', 'II Jn', 'II John'],
  '3 John': ['3 John', '3 Jn', '3Jn', '3Joh', '3Jo', 'III Jn', 'III John'],
  Jude: ['Jude', 'Jud', 'Jd'],
  Revelation: ['Revelation', 'Rev', 'Re', 'Rv', 'Apocalypse'],
};

// Book name to API book number mapping (derived from BIBLE_BOOKS order)
export const BOOK_NUMBERS: Record<string, number> = Object.fromEntries(
  Object.keys(BIBLE_BOOKS).map((book, index) => [book, index + 1])
);

// Number of chapters per book
export const BOOK_CHAPTER_COUNTS: Record<string, number> = {
  Genesis: 50, Exodus: 40, Leviticus: 27, Numbers: 36, Deuteronomy: 34,
  Joshua: 24, Judges: 21, Ruth: 4, '1 Samuel': 31, '2 Samuel': 24,
  '1 Kings': 22, '2 Kings': 25, '1 Chronicles': 29, '2 Chronicles': 36,
  Ezra: 10, Nehemiah: 13, Esther: 10, Job: 42, Psalms: 150, Proverbs: 31,
  Ecclesiastes: 12, 'Song of Solomon': 8, Isaiah: 66, Jeremiah: 52,
  Lamentations: 5, Ezekiel: 48, Daniel: 12, Hosea: 14, Joel: 3, Amos: 9,
  Obadiah: 1, Jonah: 4, Micah: 7, Nahum: 3, Habakkuk: 3, Zephaniah: 3,
  Haggai: 2, Zechariah: 14, Malachi: 4, Matthew: 28, Mark: 16, Luke: 24,
  John: 21, Acts: 28, Romans: 16, '1 Corinthians': 16, '2 Corinthians': 13,
  Galatians: 6, Ephesians: 6, Philippians: 4, Colossians: 4,
  '1 Thessalonians': 5, '2 Thessalonians': 3, '1 Timothy': 6, '2 Timothy': 4,
  Titus: 3, Philemon: 1, Hebrews: 13, James: 5, '1 Peter': 5, '2 Peter': 3,
  '1 John': 5, '2 John': 1, '3 John': 1, Jude: 1, Revelation: 22,
};
